sudo: required
services:
  - docker

before_install:
  - docker build -t mbeiswenger/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mbeiswenger/react-test npm test -- --coverage

after_success:
  - docker build -t mbeiswenger/multi-client ./client
  - docker build -t mbeiswenger/multi-nginx ./nginx
  - docker build -t mbeiswenger/multi-server ./server
  - docker build -t mbeiswenger/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mbeiswenger/multi-client
  - docker push mbeiswenger/multi-nginx
  - docker push mbeiswenger/multi-server
  - docker push mbeiswenger/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env-2
  bucket_name: elasticbeanstalk-us-east-1-722610766895
  bucket_path: docker-multi
  edge: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
